# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://aowens-21.github.io/
baseurl: /
title: Alex Owens
author: Alex Owens
description: Personal blog and resume
avatar: profile.jpg
email: aowens@u.northwestern.edu
github: aowens-21 # username
twitter: aowens_21


# needed for travis-ci build
exclude: [vendor]
